name: Release

on:
  push:
    tags:
      - "v/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build & Publish
        run: ./gradlew build publish publishMods --no-daemon
        env:
          NANITE_DEPLOY: ${{ secrets.NANITE_DEPLOY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSE_TOKEN: ${{ secrets.CURSE_DEPLOY }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
